### ISSUE TITLE
No eye paramaters?

### ISSUE THREAD

**Issue by bizzclaw** [rrazgriz/VRCFTGenerator#3]
Am I missing something, or are there no entries for SRanipal's eyetracking blendshape/setup? this tool is really nice to work with, so it would be nice if I could use this tool to generate both face and eyetracking so everything is kept consistent. Either way, really enjoying the tool. Thank you!

EDIT: Closing this as I saw Eyetracking is in your todo. I also Just had a look at VRCFTGenerator_Values.cs and I might try to add some basic ones for now for my own use. I could submit a PR, but I don't know if I'll be tackling the more complex issues you're looking for

**Comment by rrazgriz** [comment]
Yeah, to get this written down: I don't personally have an eye tracking setup, so it's a) harder for me to test the results and b) harder for me to justify the development effort. Many of the VRCFT eye parameters have special handling which I'd have to write logic for, so it's just work I haven't been able to justify spending time on yet.

[Native eye tracking](https://ask.vrchat.com/t/developer-update-2-march-2023/16706#native-eye-tracking-9) is also coming to VRChat, so that'll alleviate some of the effort. I might be able to justify it at that point, since it won't require animating the eye bones.
